name: Build and Push Docker Image for Development

on:
  push:
    branches: [ dev ]
    paths-ignore:
      - "**.md"
      - ".gitignore"

jobs:
  build-and-push:
    runs-on: Linux-ARM64-runner

    steps:
      - uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18.20.5"

      - name: Create environment files
        run: |
          echo "${{ secrets.ENV_DEV }}" > .env.dev
          
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Make build script executable
        run: chmod +x ./script/build.sh

      - name: Build and Push Docker image
        run: ./script/build.sh dev
