on:
  push:
    branches: [ main ]
    paths-ignore:
      - "**.md"
      - ".gitignore"

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.20.5"
      - run: npm install -g yarn
      - run: yarn install
