on:
  push:
    branches: [ main ]
    paths-ignore:
      - "**.md"
      - ".gitignore"

jobs:
  build-and-push:
    runs-on: Linux-ARM64-runner

    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18.20.5"

      # - name: install yarn
      #   run: npm install -g yarn

      - name: install dependencies
        run: yarn install

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Make build script executable
        run: chmod +x ./script/build-all.sh

      - name: Build and Push Docker image
        run: ./script/build-all.sh
