name: Deploy to Development

on:
  workflow_run:
    workflows: [Build and Push Docker Image for Development]
    types: [completed]
    branches: [dev]

jobs:
  deploy-dev:
    runs-on: Linux-ARM64-runner
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Execute start.sh on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USERNAME}}
          key: ${{secrets.EC2_SSH_KEY}}
          script: cd $HOME && chmod +x start_dev.sh && ./start_dev.sh
